# Generated by Django 4.0.5 on 2022-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
