# Generated by Django 4.0.5 on 2022-07-15 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0014_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
