# Generated by Django 4.0.5 on 2022-09-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_image_submittedanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedanswer',
            old_name='right_answer',
            new_name='chosen_answer',
        ),
    ]
