# Generated by Django 4.0.5 on 2022-09-08 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_quizattempts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizAttempts',
            new_name='QuizAttempt',
        ),
    ]
