# Generated by Django 4.0.5 on 2022-09-08 22:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0005_rename_quizattempts_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contestant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('points', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contestant',
                'verbose_name_plural': 'Contestants',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_avatars/')),
                ('contestant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.contestant')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_likes', to='quiz.contestant'),
        ),
    ]
