# Generated by Django 4.0.5 on 2022-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_level_profile_social_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_avatars/default_profile_pic.jpg', null=True, upload_to='profile_avatars/'),
        ),
    ]
