# Generated by Django 4.0.5 on 2022-09-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_question_quiz_alter_quiz_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
