# Generated by Django 4.0.5 on 2022-09-12 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_alter_quiz_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Quiz Completion',
                'verbose_name_plural': 'Quiz Completions',
            },
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz_imgs/'),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.AddField(
            model_name='quizcompletion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
