# Generated by Django 4.0.5 on 2022-09-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_quizcompletion_alter_quiz_image_delete_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_completions', to=settings.AUTH_USER_MODEL),
        ),
    ]
