# Generated by Django 4.0.5 on 2022-09-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quizcompletion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcompletion',
            name='user',
        ),
        migrations.AddField(
            model_name='quizcompletion',
            name='contestant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_completions', to='quiz.contestant'),
            preserve_default=False,
        ),
    ]
